# permissions for end users to view infrastructureproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infrastructureprovider-viewer-role
rules:
- apiGroups:
  - management.cluster.x-k8s.io.cluster.x-k8s.io
  resources:
  - infrastructureproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cluster.x-k8s.io.cluster.x-k8s.io
  resources:
  - infrastructureproviders/status
  verbs:
  - get
